{{- include "ffc-helm-library.container-config-map" (list . "ffc-ahwr-application.config-map") -}}
{{- define "ffc-ahwr-application.config-map" -}}
data:
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  APPLICATIONREQUEST_QUEUE_ADDRESS: {{ quote .Values.container.applicationRequestQueueAddress }}
  APPLICATIONRESPONSE_QUEUE_ADDRESS: {{ quote .Values.container.applicationResponseQueueAddress }}
  PAYMENTREQUEST_QUEUE_ADDRESS: {{ quote .Values.container.paymentRequestQueueAddress }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresExternalName }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
  POSTGRES_SCHEMA_NAME: {{ quote .Values.postgresService.postgresSchema }}
  NOTIFY_TEMPLATE_ID_FARMER_APPLICATION_COMPLETE: {{ quote .Values.container.notifyTemplateIdFarmerApplicationComplete }}
  NOTIFY_TEMPLATE_ID_FARMER_APPLICATION_CLAIM: {{ quote .Values.container.notifyTemplateIdFarmerApplicationClaim }}
  NOTIFY_TEMPLATE_ID_FARMER_CLAIM_COMPLETE: {{ quote .Values.container.notifyTemplateIdFarmerClaimComplete }}
  NOTIFY_TEMPLATE_ID_FARMER_VET_RECORD_INELIGIBLE: {{ quote .Values.container.notifyTemplateIdFarmerVetRecordIneligible }}
  NOTIFY_TEMPLATE_ID_VET_APPLICATION_COMPLETE: {{ quote .Values.container.notifyTemplateIdVetApplicationComplete }}
  SERVICE_URI: {{ quote .Values.container.serviceUri }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
{{- end -}}
