{{- include "ffc-helm-library.container-config-map" (list . "ffc-ahwr-application.config-map") -}}
{{- define "ffc-ahwr-application.config-map" -}}
data:
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  APPLICATIONDOCCREATIONREQUEST_QUEUE_ADDRESS: {{ quote .Values.container.applicationDocCreationRequestQueueAddress }}
  APPLICATIONREQUEST_QUEUE_ADDRESS: {{ quote .Values.container.applicationRequestQueueAddress }}
  APPLICATIONRESPONSE_QUEUE_ADDRESS: {{ quote .Values.container.applicationResponseQueueAddress }}
  CARBON_COPY_EMAIL_ADDRESS: {{ quote .Values.container.carbonCopyEmailAddress }}
  PAYMENTREQUEST_QUEUE_ADDRESS: {{ quote .Values.container.paymentRequestQueueAddress }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  EVENT_QUEUE_ADDRESS: {{ quote .Values.container.eventQueueAddress }}
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresqlHost }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
  POSTGRES_SCHEMA_NAME: {{ quote .Values.postgresService.postgresSchema }}
  NOTIFY_TEMPLATE_ID_FARMER_ENDEMICS_REVIEW_COMPLETE: {{ quote .Values.container.notifyTemplateIdFarmerEndemicsReviewComplete }}
  NOTIFY_TEMPLATE_ID_FARMER_ENDEMICS_FOLLOWUP_COMPLETE: {{ quote .Values.container.notifyTemplateIdFarmerEndemicsFollowupComplete }}
  SERVICE_URI: {{ quote .Values.container.serviceUri }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
  CLAIM_COMPLIANCE_CHECK_RATIO: {{ quote .Values.container.claimComplianceCheckRatio }}
  ENDEMICS_CLAIM_COMPLIANCE_CHECK_RATIO: {{ quote .Values.container.endemicsClaimComplianceCheckRatio }}
  OPTIONAL_PIHUNT_ENABLED: {{ quote .Values.container.optionalPIHuntEnabled }}
  AZURE_STORAGE_ENDEMICS_SETTINGS_CONTAINER: {{ quote .Values.container.azureStorageEndemicsSettingsContainerName }}
  SFD_MESSAGE_QUEUE_ADDRESS: {{ quote .Values.container.sfdMessageQueueAddress }}
{{- end -}}
