{{- include "ffc-helm-library.container-secret" (list . "ffc-ahwr-application.container-secret") -}}
{{- define "ffc-ahwr-application.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{ quote .Values.appInsights.key }}
  {{- end }}
  POSTGRES_USERNAME: {{ quote .Values.postgresService.postgresUser }}
  NOTIFY_API_KEY: {{ quote .Values.container.notifyApiKey }}
{{- end -}}
