version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-ahwr-application:
    build:
      target: development
    image: ffc-ahwr-application-development
    container_name: ffc-ahwr-application-development
    ports:
      - "3001:3000"
      - "9230:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  ffc-ahwr-application-postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
