version: '3.8'

services:
  ffc-ahwr-application:
    build:
      context: .
      target: production
    image: ffc-ahwr-application
    container_name: ffc-ahwr-application
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-application-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
