version: '3.8'

x-common-migration: &common-migration
  POSTGRES_HOST: ${POSTGRES_HOST:-ffc-ahwr-application-postgres}
  SCHEMA_ROLE: ${POSTGRES_SCHEMA_ROLE:-postgres}
  SCHEMA_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
  SCHEMA_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
  SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}

x-common-postgres: &common-postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: ${POSTGRES_DB:-ffc_ahwr_application}
  POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:-ppp}
  POSTGRES_USERNAME: ${POSTGRES_ADMIN_USERNAME:-postgres}

services:
  database-up:
    image: liquibase/liquibase:3.10.x
    environment:
      << : *common-migration
      << : *common-postgres
    entrypoint: >
      sh -c "/scripts/migration/database-up"
    depends_on:
      - ffc-ahwr-application-postgres
    volumes:
      - ./changelog:/liquibase/changelog
      - ./scripts:/scripts

  database-down:
    image: liquibase/liquibase:3.10.x
    environment:
      << : *common-migration
      << : *common-postgres
    entrypoint: >
      sh -c "/scripts/migration/database-down"
    depends_on:
      - ffc-ahwr-application-postgres
    volumes:
      - ./changelog:/liquibase/changelog
      - ./scripts:/scripts

  ffc-ahwr-application-postgres:
    image: postgres:11.4-alpine
    environment: *common-postgres
    ports:
      - "5432:5432"    
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
