version: '3.8'

services:
  ffc-ahwr-application:
    build:
      context: .
      target: production
    image: ffc-ahwr-application
    container_name: ffc-ahwr-application
    depends_on:
      - ffc-ahwr-application-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-application-local
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      CARBON_COPY_EMAIL_ADDRESS: ${CARBON_COPY_EMAIL_ADDRESS}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      EVENT_QUEUE_ADDRESS: ${EVENT_QUEUE_ADDRESS:-ffc-ahwr-event}${MESSAGE_QUEUE_SUFFIX}
      APPLICATIONDOCCREATIONREQUEST_QUEUE_ADDRESS: ${APPLICATIONDOCCREATIONREQUEST_QUEUE_ADDRESS:-ffc-ahwr-document-request}${MESSAGE_QUEUE_SUFFIX}
      APPLICATIONRESPONSE_QUEUE_ADDRESS: ${APPLICATIONRESPONSE_QUEUE_ADDRESS:-ffc-ahwr-application-response}${MESSAGE_QUEUE_SUFFIX}
      APPLICATIONREQUEST_QUEUE_ADDRESS: ${APPLICATIONREQUEST_QUEUE_ADDRESS:-ffc-ahwr-application-request}${MESSAGE_QUEUE_SUFFIX}
      PAYMENTREQUEST_QUEUE_ADDRESS: ${PAYMENTREQUEST_QUEUE_ADDRESS:-ffc-ahwr-payment-request}${MESSAGE_QUEUE_SUFFIX}
      POSTGRES_DB: ffc_ahwr_application
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-ahwr-application-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      NOTIFY_API_KEY: ${NOTIFY_API_KEY:-examplekey-644a2a30-7487-4e98-a908-b5ecd82d5225-644a2a30-7487-4e98-a908-b5ecd82d5225}
      NOTIFY_TEMPLATE_ID_FARMER_APPLICATION_CLAIM: ${NOTIFY_TEMPLATE_ID_FARMER_APPLICATION_CLAIM:-644a2a30-7487-4e98-a908-b5ecd82d5225}
      NOTIFY_TEMPLATE_ID_FARMER_CLAIM_COMPLETE: ${NOTIFY_TEMPLATE_ID_FARMER_CLAIM_COMPLETE:-644a2a30-7487-4e98-a908-b5ecd82d5225}
      NOTIFY_TEMPLATE_ID_FARMER_VET_RECORD_INELIGIBLE: ${NOTIFY_TEMPLATE_ID_FARMER_VET_RECORD_INELIGIBLE:-644a2a30-7487-4e98-a908-b5ecd82d5225}
      NOTIFY_TEMPLATE_ID_VET_APPLICATION_COMPLETE: ${NOTIFY_TEMPLATE_ID_VET_APPLICATION_COMPLETE:-644a2a30-7487-4e98-a908-b5ecd82d5225}
      SERVICE_URI: http://localhost:3000
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      COMPLIANCE_APPLICATION_COUNT: 5
      COMPLIANCE_SCHEDULER: "0 9 * * 2-3"
      RBAC_ENABLED: ${RBAC_ENABLED:-false}

  ffc-ahwr-application-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_ahwr_application
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
