environment: development
name: ffc-ahwr-application
namespace: ffc-ahwr
workstream: ffc-ahwr
image: ffc-ahwr-application

labels: {}

aadPodIdentity: true

appInsights:
  key:

azureIdentity:
  clientID:
  resourceID:

containerConfigMap:
  name: ffc-ahwr-application-config-map

containerSecret:
  name: ffc-ahwr-application-container-secret
  type: Opaque

deployment:
  cpuThreshold: 40
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 2
  priorityClassName: default
  restartPolicy: Always
  replicas: 1

container:
  applicationRequestQueueAddress: ffc-ahwr-application-request
  applicationResponseQueueAddress: ffc-ahwr-application-response
  imagePullPolicy: IfNotPresent
  messageQueueHost: namespace.servicebus.windows.net
  limitMemory: 40Mi
  limitCpu: 40m
  port: 3000
  requestCpu: 10m
  requestMemory: 10Mi

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
