environment: development
name: ffc-ahwr-application
namespace: ffc-ahwr
workstream: ffc-ahwr
image: ffc-ahwr-application

labels: {}

aadPodIdentity: true

appInsights:
  key:

azureIdentity:
  clientID:
  resourceID:

containerConfigMap:
  name: ffc-ahwr-application-config-map

containerSecret:
  name: ffc-ahwr-application-container-secret
  type: Opaque

deployment:
  cpuThreshold: 40
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 2
  priorityClassName: default
  restartPolicy: Always
  replicas: 1

container:
  applicationRequestQueueAddress: ffc-ahwr-application-request
  applicationResponseQueueAddress: ffc-ahwr-application-response
  imagePullPolicy: IfNotPresent
  messageQueueHost: namespace.servicebus.windows.net
  limitMemory: 100Mi
  limitCpu: 80m
  port: 3000
  requestCpu: 40m
  requestMemory: 80Mi
  notifyApiKey: example-644a2a30-7487-4e98-a908-b5ecd82d5225-644a2a30-7487-4e98-a908-b5ecd82d5225
  notifyTemplateIdApplicationComplete: 644a2a30-7487-4e98-a908-b5ecd82d5225
  notifyTemplateIdVetApplicationComplete: 644a2a30-7487-4e98-a908-b5ecd82d5225

postgresService:
  postgresDb: ffc_ahwr_application
  # postgresExternalName is the external host name to which PostgreSQL
  # requests should be forwarded. If empty, PostgreSQL is assumed to be
  # within the cluster and accessible via postgresHost
  postgresExternalName:
  postgresHost: ffc-ahwr-application-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres


livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
