environment: development
image: ffc-ahwr-application
name: ffc-ahwr-application
namespace: ffc-ahwr
workstream: ffc-ahwr

labels: {}

aadPodIdentity: true

appInsights:
  connectionString:

azureIdentity:
  clientID:
  resourceID:

containerConfigMap:
  name: ffc-ahwr-application-config-map

containerSecret:
  name: ffc-ahwr-application-container-secret
  type: Opaque

deployment:
  cpuThreshold: 40
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 2
  priorityClassName: default
  restartPolicy: Always
  replicas: 1

container:
  applicationDocCreationRequestQueueAddress: ffc-ahwr-document-request
  applicationRequestQueueAddress: ffc-ahwr-application-request
  applicationResponseQueueAddress: ffc-ahwr-application-response
  carbonCopyEmailAddress:
  paymentRequestQueueAddress: ffc-ahwr-payment-request
  imagePullPolicy: IfNotPresent
  limitMemory: 100Mi
  limitCpu: 80m
  messageQueueHost: namespace.servicebus.windows.net
  notifyApiKey: example-644a2a30-7487-4e98-a908-b5ecd82d5225-644a2a30-7487-4e98-a908-b5ecd82d5225
  notifyTemplateIdFarmerApplicationComplete: 644a2a30-7487-4e98-a908-b5ecd82d5225
  notifyTemplateIdFarmerApplicationClaim: 644a2a30-7487-4e98-a908-b5ecd82d5225
  notifyTemplateIdFarmerClaimComplete: 644a2a30-7487-4e98-a908-b5ecd82d5225
  notifyTemplateIdFarmerVetRecordIneligible: 644a2a30-7487-4e98-a908-b5ecd82d5225
  notifyTemplateIdVetApplicationComplete: 644a2a30-7487-4e98-a908-b5ecd82d5225
  port: 3000
  requestCpu: 40m
  requestMemory: 80Mi
  eventQueueAddress: ffc-ahwr-event
  serviceUri:
  azureStorageConnectionString:
  azureStorageUseConnectionString: true
  azureStorageAccountName:
  complianceApplicationCount: 5
  rbacEnabled:

postgresService:
  postgresDb: ffc_ahwr_application
  postgresExternalName: namespace.postgres.database.azure.com
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres


livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  path: /healthz
  periodSeconds: 10
  port: 3000

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  path: /healthy
  periodSeconds: 10
  port: 3000
