openapi: 3.0.3
info:
  title: Application API
  description: |-
    Application API for Animal Health and Welfare Review
  version: 0.30.3
tags:
  - name: application
    description: Everything about applications.
paths:
  /api/application/get/{ref}:
    get:
      tags:
        - application
      summary: Get application by reference number
      description: Returns an application object when given a valid reference number
      operationId: getApplicationByReference
      parameters:
        - name: ref
          in: path
          description: The reference number for the application.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The application was found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getApplicationByRef'
        '404':
          description: The reference is ineligible or was not found.
        '5XX':
          description: Unexpected error.
  /api/application/search:
    post:
      tags:
        - application
      summary: Search application by Search Type and Search Text.
      description: Currently Support Status, SBI number, Application Reference Number
      operationId: searchApplication
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/applicationSearch'
        required: true
      responses:
        '200':
          description: The search was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/applicationSearchResponse'
        '5XX':
          description: Unexpected error.
  /api/application/getAllGroupedBySbiNumbers:
    get:
      tags:
        - application
      summary: Get application by SBI number
      description: Get all applications grouped by Single Business Identifier (SBI) numbers.
      operationId: getApplicationBySBI
      parameters:
        - name: sbi
          in: query
          description: The sbi numbers that you want to query with.
          required: true
          schema:
            type: array
            items:
              type: string
              example: "123456789"
      responses:
        '200':
          description: The applications were found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getApplicationBySbi'
        '5XX':
          description: Unexpected error.
components:
  schemas:
    getApplicationByRef:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "eaf9b180-9993-4f3f-a1ec-4422d48edf92"
        reference:
          type: string
          example: "AHWR-5C1C-DD6A"
        data:
          type: string
          example: "Placeholder Data"
        claimed:
          type: boolean
          example: false
        createdAt:
          type: string
          example: "2023-01-17 13:55:20"
        updatedAt:
          type: string
          example: "2023-01-17 13:55:20"
        createdBy:
          type: string
          example: "David Jones"
        updatedBy:
          type: string
          example: "David Jones"
        statusId:
          type: integer
          example: 123
        status:
          type: string
          example: "AGREED"
    getApplicationBySbi:
      type: object
      properties:
        sbi:
          type: integer
          example: 123456789
        applications:
          type: array
          items:
            type: object
            properties: 
              reference:
                type: string
                example: "AHWR-5C1C-DD6A"
              status: 
                type: string
                example: AGREED
    applicationSearch:
      type: object
      properties:
        offset:
          type: number
          example: 0
          default: 0     
        limit:
          type: number
          example: 1
          default: 20   
          minimum: 0
        search:
          type: object
          properties:
            text: 
              type: string
              example: "Search Query"
            type:
              type: string
              example: "sbi"
              default: "sbi"   
        sort:
          type: object
          properties:
            field: 
              type: string
              example: "CREATEDAT"
              default: "CREATEDAT"
            direction:
              type: string
              example: "ASC"
              enum: ["ASC"]
        filter: 
          type: array
          items: {}
    applicationSearchResponse:
      type: object
      properties:
        applications:
          type: array
          items:
            type: object
            properties:
              application:
                type: object
                properties:
                  id:
                    type: string
                    example: "eaf9b180-9993-4f3f-a1ec-4422d48edf92"
                  reference:
                    type: string
                    example: "AHWR-5C1C-DD6A"
                  data:
                    type: string
                    example: "Placeholder Data"
                  claimed:
                    type: boolean
                    example: false
                    default: false
                  createdAt:
                    type: string
                    example: "2023-01-17 13:55:20"
                  updatedAt:
                    type: string
                    example: "2023-01-17 13:55:20"
                    default: null
                  createdBy:
                    type: string
                    example: "David Jones"
                  updatedBy:
                    type: string
                    example: "David Jones"
                    default: null
                  statusId:
                    type: integer
                    example: 123
        total:
          type: integer
          example: 10
        applicationStatus:
          type: array
          items:
            type: string
            example: "AGREED"